# Generated by Django 5.2.10 on 2026-01-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('image_url', models.URLField(blank=True, help_text='External URL if not uploading image', max_length=500, null=True)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='colleges/hero/')),
                ('about', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('seats', models.CharField(blank=True, max_length=50)),
                ('fees', models.CharField(blank=True, max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.college')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='api.college')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
