# Generated by Django 5.2.10 on 2026-01-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('ayurveda', 'Ayurveda'), ('homeo', 'Homeo'), ('naturopathy', 'Naturopathy')], default='medical', max_length=50),
        ),
    ]
