# Generated by Django 5.0.1 on 2026-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_college_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
