# Generated by Django 5.0.1 on 2026-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_college_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(default='Quick Enquiry', max_length=50),
        ),
    ]
